#!/bin/bash
#SBATCH --job-name=data-proc
#SBATCH --partition=gpu-a40
#SBATCH --account=ark
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --gres=gpu:1
#SBATCH --time=04:59:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=tjung2@uw.edu

# I use source to initialize conda into the right environment.
cat $0
echo "--------------------"

source ~/.bashrc
conda activate ckl

python run.py --config configs/templama/evaluation/t5_kadapters_2011.json
python run.py --config configs/templama/evaluation/t5_kadapters_2012.json
python run.py --config configs/templama/evaluation/t5_kadapters_2013.json
python run.py --config configs/templama/evaluation/t5_kadapters_2014.json
python run.py --config configs/templama/evaluation/t5_kadapters_2015.json
python run.py --config configs/templama/evaluation/t5_kadapters_2016.json
python run.py --config configs/templama/evaluation/t5_kadapters_2017.json
python run.py --config configs/templama/evaluation/t5_kadapters_2018.json
python run.py --config configs/templama/evaluation/t5_kadapters_2019.json
python run.py --config configs/templama/evaluation/t5_kadapters_2020.json
