program: run.py
project: temporal_questions
method: grid
parameters:
  learning_rate: 
    values: [1e-3, 1e-4, 1e-5]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --config
  - configs/templama/training/t5_kadapters_yearly_2freeze.json
