wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.12.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: em_score
      6:
      - 3
      7:
      - 2
    - 1: f1_score
      6:
      - 3
      7:
      - 2
    python_version: 3.8.13
    start_time: 1660735605
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 7
      4: 3.8.13
      5: 0.12.21
      6: 4.12.3
      8:
      - 5
