wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1660870605.634017
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 19
      - 23
      4: 3.8.13
      5: 0.13.1
      8:
      - 5
epochs:
  desc: null
  value: 1
